### ISSUE TITLE
Construir Protótipo US05

### ISSUE THREAD

**Issue by OscarDeBrito** [fga-eps-mds/2023-1-CAPJu-Doc#139]

**Comment by faco400** [comment]
## Descrição
Foram criados os protótipos abaixo

## Protótipo 
[Tela de adição de etapa no fluxo com duração de etapas](https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2255-6552&scaling=min-zoom&page-id=2102%3A2109)
[Tela de edição de etapa no fluxo com duração de etapas](https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2231-8901&scaling=min-zoom&page-id=2102%3A2109)
[Tela de edição de etapa no fluxo com duração de etapas com erro](https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2264-9095&scaling=min-zoom&page-id=2102%3A2109)

## Critérios de aceitação
- [ ] Definir duração da etapa na criação/edição de fluxo
- [ ] Visualizar duração de etapas no fluxo 
- [ ] É obrigatório o preenchimen
