### ISSUE TITLE
US37 - Gerenciamento de etapas

### ISSUE THREAD

**Issue by faco400** [fga-eps-mds/2023-1-CAPJu-Doc#154]
## Descrição.
Eu como: Estágiario, Servidor, Diretor, Juiz, Administrador
desejo: separar etapas por unidade
para que eu possa: visualizar as etapas da minha unidade

## Como solucionar <Nao necessario>
Alterar a visualização para que os usuários ao acessar a aba de etas vejam apenas as etapas criadas dentro de sua unidade
  
## Prioridade
**Must**

## Critérios de aceitação
- [x] Usuário de uma unidade X deve apenas visualizar etapas da Unidade X

## Tarefas:
Backend:
- [x] #169

**Comment by senaarth** [comment]
Nessa não precisa alterar o recebimento no front, já que ele vai so receber os dados ja filtrados do backend

**Comment by senaarth** [comment]
Boa noite @well1981, us disponivel para validação, segue o link https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Registro a validação da implementação (etapa não aparece para usuário de outra unidade).
