### ISSUE TITLE
US38 - Gerenciamento de processos

### ISSUE THREAD

**Issue by senaarth** [fga-eps-mds/2023-1-CAPJu-Doc#163]
## Descrição.
Eu como: Estágiario, Servidor, Diretor, Juiz, Administrador
desejo: separar processos por unidade
para que eu possa: visualizar os processos da minha unidade

## Como solucionar <Nao necessario>
Alterar a visualização para que os usuários ao acessar a aba de processos vejam apenas os processos criadas dentro de sua unidade
  
## Prioridade
**Must**

## Critérios de aceitação
- [x] Usuário de uma unidade X deve apenas visualizar processos da Unidade X

## Tarefas:
Backend:
- [x] Alterar endpoint de listagem de processos para retornar apenas os da unidade do usuário

**Comment by senaarth** [comment]
Boa noite @well1981, us disponivel para validação, segue o link https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Registro a validação da implementação (usuário de uma unidade não visualiza o processo de outra unidade).
