### ISSUE TITLE
US39 - Gerenciamento de cadastro

### ISSUE THREAD

**Issue by senaarth** [fga-eps-mds/2023-1-CAPJu-Doc#164]
## Descrição.
Eu como: Diretor
desejo: separar cadastro por unidade
para que eu possa: visualizar as solicitações e usuários da minha unidade

## Como solucionar <Nao necessario>
Alterar a visualização para que os usuários ao acessar a aba de cadastro vejam apenas os usuários de sua unidade
  
## Prioridade
**Must**

## Critérios de aceitação
- [x] Usuário de uma unidade X deve apenas visualizar usuários da Unidade X

## Tarefas:
Backend:
- [x] Alterar endpoint de listagem de usuários para retornar apenas as da unidade do usuário

**Comment by senaarth** [comment]
Boa noite @well1981, us disponivel para validação, segue o link https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Valido a implementação (não é possível autorizar/editar a solicitação de cadastro de usuário de outra unidade). Todos os usuários devem aparecer no perfil de acesso com restrição das ações editar e remover (possível apenas para administrador e diretor). Diretor pode remover e editar outro Diretor da mesma unidade.
