### ISSUE TITLE
US34 - Início do processo

### ISSUE THREAD

**Issue by senaarth** [fga-eps-mds/2023-1-CAPJu-Doc#165]
## Descrição.
Eu como: Servidor, Diretor, Administrador
desejo: poder iniciar um processo
para que eu possa: dar prosseguimento num processo ainda nao iniciado

## Prioridade
**Must**

## Critérios de aceitação
- [x] Deve haver um botão de iniciar processo quando o processo ainda não tiver sido iniciado

## Tarefas:
Frontend:
- [x] #171

**Comment by well1981** [comment]
Valido a implementação da US34 (teste realizado na reunião semanal).
