### ISSUE TITLE
US35 - Finalizar processo

### ISSUE THREAD

**Issue by senaarth** [fga-eps-mds/2023-1-CAPJu-Doc#166]
## Descrição.
Eu como: Servidor, Diretor, Administrador
desejo: poder finalizar um processo
para que eu possa: oficializar o fim de um processo que já tenha terminado a última etapa

## Prioridade
**Must**

## Critérios de aceitação
- [x] Deve haver um botão de finalizar processo quando o processo já estiver na última etapa

## Tarefas:
Backend:
- [ ] Criar Endpoint para alterar status do processo no fluxo para finalizado

Frontend:
- [x] #172
- [x] #173

**Comment by well1981** [comment]
Valido a implementação da US35 (teste realizado na reunião semanal).
