### ISSUE TITLE
Criar botão de finalizar processo

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#172]
Criar botão de finalizar processo.

**Comment by GuilhermeDSa1013** [comment]
# BUG
A visualização das etapas do processo no fluxo estão seguindo a ordem alfabética, não a ordem de criação das etapas. Por conta disso as datas de vencimento não estão condizentes. 

![Captura de tela de 2023-05-28 20-55-50](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/92813703/b039540e-3a2d-4ac2-9519-1d7de9e46d6e)
![Captura de tela de 2023-05-28 20-57-00](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/92813703/f8d26d85-05f4-4c0b-a211-010bc0b472bd)

**Comment by wellpriz** [comment]
Com base no relato acima issue de bug aberta #174
