### ISSUE TITLE
BUG - Visualizar Processo no Fluxo

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#174]
## Descrição.
De acordo com relato do pareamento do squad 2 segue a descrição do bug encontrado.
# BUG
  ### Issue Relacionada - Criar botão de finalizar processo #172 
A visualização das etapas do processo no fluxo estão seguindo a ordem alfabética, não a ordem de criação das etapas. Por conta disso as datas de vencimento não estão condizentes. 

![Captura de tela de 2023-05-28 20-55-50](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/92813703/b039540e-3a2d-4ac2-9519-1d7de9e46d6e)
![Captura de tela de 2023-05-28 20-57-00](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/92813703/f8d26d85-05f4-4c0b-a211-010bc0b472bd)

**Comment by senaarth** [comment]
dando seguimento nisso agora
