### ISSUE TITLE
US41 - Observações sobre o avanço de etapa

### ISSUE THREAD

**Issue by faco400** [fga-eps-mds/2023-1-CAPJu-Doc#185]
## Descrição.
Eu como: Estágiario, Servidor, Diretor, Juiz, Administrador
desejo poder: adicionar a uma observação sobre o avanço em cada etapa do processo
para que eu possa: Ver detalhes/informações especificas sobre o avanço de um processo

## Protótipo
![image](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/122410504/4132d117-12c6-4ac3-b818-5dd04810ed14)

## Prioridade
**MUST**
  
## Critérios de aceitação

- [x] Reinserir opção de adicionar comentário entre etapas.

**Comment by well1981** [comment]
Deve ser possível escrever observações sobre o avanço de etapa > A anotação de uma observação não é obrigatória no avanço de uma etapa (não precisa abrir o modal com caixa de texto). Se o usuário quiser, faz a anotação utilizando a funcionalidade "+adicionar nova observação" no caminho entre as etapas.

**Comment by well1981** [comment]
Valido o novo critério de aceitação: "Reinserir opção de adicionar comentário entre etapas".

**Comment by well1981** [comment]
Válido o protótipo.

**Comment by well1981** [comment]
O perfil de Diretor não permitiu iniciar o processo. Segue a mensagem de erro:
Erro ao atualizar status do processo no fluxo
Acesso Negado: Perfil sem permissão
Não pude validar a US.

**Comment by well1981** [comment]
Erro anterior permanece. Teste feito no perfil de administrador, após conceder permissão. Novo erro informado pelo sistema:
Erro ao adicionar observação
Erro ao criar observação: SequelizeDatabaseError: value too long for type character varying(100)
