### ISSUE TITLE
Criar página de cadastro

### ISSUE THREAD

**Issue by victordsantoss** [fga-eps-mds/2023-1-CAPJu-Doc#27]
# Página de Cadastro

## Descrição.
Uma nova tela de cadastro deve ser criada seguindo os novos padrões de UX/UI disponibilizados no [Figma](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu?node-id=0-1&t=7i5HiJSx0rGY6MOK-0).

## Critérios de aceitação

- [x] Tela de Cadastro

**Comment by senaarth** [comment]
Fechando pois foi finalizada nesse [commit](https://github.com/fga-eps-mds/2023-1-CAPJu-Front/commit/3b981248d24c18fd2bb2550f817c3a84ddee694d).
