### ISSUE TITLE
Criar componente de abas de Navegação

### ISSUE THREAD

**Issue by victordsantoss** [fga-eps-mds/2023-1-CAPJu-Doc#28]
# Componente de abas de navegação

## Descrição.
 Deve ser criado um componente para as abas de navegação seguindo os novos padrões de UX/UI disponibilizados no [Figma](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu?node-id=0-1&t=7i5HiJSx0rGY6MOK-0).
  
## Critérios de aceitação

- [ ] Componente de abas de navegação

**Comment by senaarth** [comment]
Fechado nesse [pr](https://github.com/fga-eps-mds/2023-1-CAPJu-Front/pull/2)
