### ISSUE TITLE
Criar componente de tabelas

### ISSUE THREAD

**Issue by victordsantoss** [fga-eps-mds/2023-1-CAPJu-Doc#29]
# Componente de tabelas

## Descrição.
Deve ser criado um componente para tabelas seguindo os novos padrões de UX/UI disponibilizados no [Figma](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu?node-id=0-1&t=7i5HiJSx0rGY6MOK-0).
  
## Critérios de aceitação

- [x] Componente de tabelas

**Comment by senaarth** [comment]
Fechado nesse [PR](https://github.com/fga-eps-mds/2023-1-CAPJu-Front/pull/5)
