### ISSUE TITLE
Criar página de edição de conta

### ISSUE THREAD

**Issue by victordsantoss** [fga-eps-mds/2023-1-CAPJu-Doc#30]
# Criar página de edição de conta

## Descrição.

Deve ser criada um página de edição de conta juntamente com ações de edição de e-mail e senha, seguindo o  novo layout disponibilizado no [Figma](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu?node-id=0-1&t=7i5HiJSx0rGY6MOK-0).
  
## Critérios de aceitação

- [x] Tela de edição de conta
- [x] Formulário de edição de email
- [x] Formulário de edição de senha

**Comment by senaarth** [comment]
Fechada nesse [PR](https://github.com/fga-eps-mds/2023-1-CAPJu-Front/pull/3)
