### ISSUE TITLE
Criar página de solicitações e perfil de acesso

### ISSUE THREAD

**Issue by victordsantoss** [fga-eps-mds/2023-1-CAPJu-Doc#31]
# Página de solicitações e perfil de acesso

## Descrição.
Deve ser criada um página de visualização de solicitações  de acesso juntamente com suas determinadas ações, seguindo o novo layout disponibilizado no [Figma](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu?node-id=0-1&t=7i5HiJSx0rGY6MOK-0).
  
## Critérios de aceitação

- [x] Tela de solicitação de acessos
- [x] Listagem de solicitações no componente tabular 
- [x] Ações de aceitar e recusar

**Comment by senaarth** [comment]
Fechado neste [PR](https://github.com/fga-eps-mds/2023-1-CAPJu-Front/pull/6)
