### ISSUE TITLE
US01 - Experiencia com a  plataforma

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#58]
## Descrição.

**Eu como:** Estagiário, Servidor, Diretor, Juiz ou Administrador
**desejo:** utilizar uma plataforma com a identidade visual definida e ações padronizadas
**para que eu possa:** obter uma melhor e mais fácil experiência como usuário.

## Protótipo 
Clique [aqui](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=148-2857&t=VjdvjBk4WdQMTx6Q-0) para acessar o protótipo geral com todas as telas, **se necessário**.

## Como solucionar
Visualizar as telas abaixo e verificar a padronização do layout.

[Tela de Gerenciamento de Unidades (Visualizar, Excluir, Ver diretores e Adicionar Diretores)](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu?type=design&node-id=29-4457&scaling=min-zoom&page-id=0%3A1)

## Prioridade 
**MUST**
  
## Critérios de aceitação
- [x] A interface deverá ter ações de Visualizar, Editar e Remover padronizadas
- [x] A interface deverá ter alertas padronizados
- [x] A interface deverá ter botões padronizados
- [x] A interface deverá ter títulos e textos padronizados
- [x] A interface deverá ter um menu dinâmico om opções desabilitadas conforme as permissões 

### Protótipo
- [x] #137

**Comment by senaarth** [comment]
Vale lembrar que o protótipo inicial já foi validado com o Wellignton e ele fez alguns comentários, o desenvolvimento está sendo feito levando em consideração esse feedback. Para fins de rastreabilidade vou deixá-lo aqui:

- Remoção do input de sequencias, seguir a sequencia colocada pelo usuario;
- Manter funcionalidades não disponiveis para usuario visiveis, porem desativadas;
- Observação no cadastro: esta etapa consiste apenas em uma solicitação de cadastro. o efetivo login no sistema será possível após a aprovação de sua solicitação;
- Esqueci sua senha está faltando;
- Adicionar coluna indicando fluxo do processo na listagem de processos;
- Remover coluna de etapa final e substituir por Percentual Percorrido no Fluxo (X/Y);
- Padronizar texto de adição/criação => criação;
- Mudar palabra “Notificação” para “Observação”;
- Atualizar solicitações, ação de visualizar;
- Detalhar ações no controle de perfil;
-

**Comment by well1981** [comment]
Critérios de aceitação validados (dei o check). A análise está restrita à interface.

**Comment by senaarth** [comment]
Boa noite @well1981, a história já está implementada e disponível para validação, segue link de teste:

https://develop--capju.netlify.app/

Assim que possível favor retornar com seus comentários.

**Comment by well1981** [comment]
Valido a implementação da US01. Registro que faltou a ação "editar" em UNIDADES e ETAPAS.
