### ISSUE TITLE
US02 - Informações de acesso

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#59]
## Descrição.

**Eu como:** Diretor ou Administrador
**desejo:** acessar uma página sobre os acessos da plataforma
**para que eu possa:** ver de forma centralizada tanto as solicitações de acesso quanto os perfis dos usuários já existentes.

## Protótipo 
Clique [aqui](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=148-2857&t=VjdvjBk4WdQMTx6Q-0) para acessar o protótipo geral com todas as telas, **se necessário**.

## Como solucionar
Visualizar as telas abaixo para verificar os critérios de aceitação.

[Tela de listagem de solicitações e perfil de acesso](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-2769&scaling=min-zoom&page-id=148%3A2857)

## Prioridade 
**MUST**
  
## Critérios de aceitação
- [x]  A interface deverá ter a listagem de solicitações de acesso.
- [x]  A interface deverá ter a listagens dos perfis com acesso à plataforma.

### Front
- [x] #114
### Protótipo

- [x] #140

**Comment by senaarth** [comment]
Vale lembrar que o propósito dessa página não é criar uma nova e sim juntar as duas que já existem (Solicitações e Perfil de Acesso) numa aba só chamada cadastro.

**Comment by well1981** [comment]
Critérios de aceitação validados (dei o check). A análise está restrita à interface. A consolidação das funcionalidades em "cadastro" só ocorreu a partir da tela 5 da apresentação. Favor retirar a vírgula da mensagem emitida na tela 8 da apresentação.

**Comment by senaarth** [comment]
Boa noite @well1981, a história já está implementada e disponível para validação, segue link de teste:

https://develop--capju.netlify.app/

Assim que possível favor retornar com seus comentários.

**Comment by well1981** [comment]
Valido a implementação da US02. Registro as seguintes observações:
- ajustar a mensagem de erro na solicitação de acesso quando se tratar do mesmo CPF
- adicionar a ação "visualizar" na aba cadastro e em ambos os quadros (solicitações e perfil de acesso). Pedido feito para melhor visualização do usuário.
