### ISSUE TITLE
Atualização das Atas

### ISSUE THREAD

**Issue by faco400** [fga-eps-mds/2023-1-CAPJu-Doc#62]
## Descrição.
Atualizar atas das reuniões

## Como solucionar <Nao necessario>
Acessar os documentos das atas anteriores e documentar no gh-pages. Ver canal do CapJU no Discord para acessar documentos anteriores. No momento é criado um arquivo .md para cada semana na pasta [docs/Relatorios/](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/tree/main/docs/Relat%C3%B3rios) e também atualizado o arquivo [docs/Relatorios/relatorios_do_projeto.md](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/blob/main/docs/Relat%C3%B3rios/relatorios_do_projeto.md)  com a semana de cada ata registrada
  
## Critérios de aceitação

- [ ] Atualizar atas do gh-pages

**Comment by wellpriz** [comment]
Atualizar as Atas da sprint 2

**Comment by GuilhermeDSa1013** [comment]
Atualizar a ata da Sprint 2, com as issues concluídas na Sprint

**Comment by GuilhermeDSa1013** [comment]
Criar relatório da Sprint 3

**Comment by GuilhermeDSa1013** [comment]
Criar relatório da Sprint 4

**Comment by GuilhermeDSa1013** [comment]
Criar relatório da Sprint 5

**Comment by GuilhermeDSa1013** [comment]
Criar relatório da Sprint 6 e 7

**Comment by GuilhermeDSa1013** [comment]
Criar relatório da Sprint 8
