### ISSUE TITLE
US03 - Retrocesso de Etapas

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#64]
## Descrição.
Eu como: Estágiario, Servidor, Diretor, Juiz, Administrador 
desejo ter:  um botão de retrocesso de etapa
para que eu possa: voltar uma etapa em um processo caso seja necessário

## Protótipo 
[Página de processo com botão de retroceder etapa.](https://www.figma.com/proto/Vsu65sB8tttg1SoRayhBp7/Prot%C3%B3tipos-Sprint---A?type=design&node-id=1-816&scaling=min-zoom&page-id=0%3A1)
[Modal de confirmação de retrocesso de etapa.](https://www.figma.com/proto/Vsu65sB8tttg1SoRayhBp7/Prot%C3%B3tipos-Sprint---A?type=design&node-id=1-835&scaling=min-zoom&page-id=0%3A1)

## Credenciais de acesso
cpf: [12345678901](tel:12345678901)
senha: 123Teste

## Prioridade 
**SHOULD**
  
## Critérios de aceitação

- [x] Deve ser possível retroceder a etapa de um processo

### Protótipo
- [x] #135
### Frontend

**Comment by well1981** [comment]
O critério de aceitação foi validado. Apenas uma observação: trocar o texto da caixa de diálogo de "Retroceder **### de** Etapa" para "Retroceder Etapa".

**Comment by well1981** [comment]
Valido a implementação da US03 (teste realizado na reunião semanal).
