### ISSUE TITLE
US04 - Adição de etapas com nomes iguais, mas durações diferentes

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#65]
## Descrição.
Eu como: Estágiario, Servidor, Diretor, Juiz, Administrador 
desejo poder: adicionar etapas com o mesmo nome, porém de duração diferentes  
para que eu possa: variar o uso de determinada etapa

## Protótipo 
Não tem

## Credenciais de acesso
cpf: [12345678901](tel:12345678901)
senha: 123Teste
  
## Prioridade 
**MUST**

## Critérios de aceitação

- [x] Deve ser possível criar uma etapa com nome repetido

### Backend

**Comment by well1981** [comment]
Critério de aceitação validado.

**Comment by senaarth** [comment]
Plataforma já possibilita a adição  de etapas com nomes iguais, mas durações diferentes.
