### ISSUE TITLE
US06 - Status do processo

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#67]
## Descrição.
Eu como: Estagiário, Servidor, Diretor, Juiz, Administrador 
desejo poder: visualizar o status de um processo
para que eu possa: saber como está o andamento de um processo

## Credenciais de acesso
cpf: [12345678901](tel:12345678901)
senha: 123Teste

## Prioridade 
**MUST**
  
## Critérios de aceitação

- [x] Deve ser possível visualizar o status de um processo na tabela de processos
- [x] Deve ser possível visualizar o status de um processo na página de visualização do mesmo

### Protótipo
- [x] #141

**Comment by well1981** [comment]
O botão iniciar e o aviso correspondente estão corretos. Só não entendi porque o botão "iniciar processo" aparece sozinho sem os demais ao lado. 

Se "arquivar processo" é uma ação que pode ser feita a qualquer momento e "finalizar processo" somente pode ser selecionada se o processo estiver na última etapa, está tudo correto.

**Comment by well1981** [comment]
Valido o critério de aceitação com a observação acima.

**Comment by well1981** [comment]
Valido a implementação da US06 (teste realizado na reunião semanal).
