### ISSUE TITLE
US07 - Registro de data por etapa

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#68]
## Descrição.
Eu como: Estágiario, Servidor, Diretor, Juiz, Administrador 
desejo poder: adicionar a data de entrada em cada etapa do processo
para que eu possa: conseguir especificar/ver as datas de entrada em cada etapa

## Protótipo 
[Tela de processos com data de entrada e vencimento](https://www.figma.com/proto/8ezZPyFKvCMRPhY8uQ6hrc/Prot%C3%B3tipos-Sprint---B?type=design&node-id=2-821&scaling=min-zoom&page-id=0%3A1)

## Credenciais de acesso
cpf: [12345678901](tel:12345678901)
senha: 123Teste

## Prioridade 
**MUST**
  
## Critérios de aceitação

- [x] Deve ser possível visualizar no processo a data em que foi dada entrada em cada etapa já iniciada/finalizada.

### Protótipo
- [x] #141

**Comment by well1981** [comment]
Valido os seguintes critérios de aceitação:
- Deve ser possível escrever observações sobre o avanço de etapa
- Deve ser possível visualizar no processo a data em que foi dada entrada em cada etapa já iniciada/finalizada

Sobre o critério de aceitação "Deve ser possível adicionar uma data especificando a entrada naquela etapa", o usuário não precisa inserir data e hora, pois basta a aplicação obter automaticamente essa informação quando ele clicar no avançar etapa.

**Comment by senaarth** [comment]
Os critérios e protótipos foram atualizados de acordo com a validação.

**Comment by well1981** [comment]
Valido o desmembramento da US (nova US criada).

**Comment by well1981** [comment]
Válido a implementação com as seguintes observações: o texto explicativo deve estar no tutorial; alterar texto da caixa (resumido: nome e vencimento).
