### ISSUE TITLE
US08 - Controle de unidades

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#70]
## Descrição.

**Eu como:** Administrador
**desejo:** remover uma unidade
**para que eu possa:** controlar as unidades cadastradas. 

## Como solucionar
Acrescentar um botão de remover unidade na lista de unidades. A unidade excluida não deverá ser exibida na listagem.

## Protótipo
[Tela com listagem de Unidades](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-2740&scaling=min-zoom&page-id=148%3A2857)

[Tela de exclusão de unidade](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-3173&scaling=min-zoom&page-id=148%3A2857)

## Prioridade
**MUST**
  
## Critérios de aceitação

- [x] Visualizar botão de remover Unidade
- [x] Unidade deve ser removida da lista de unidades

### Protótipo
- [x] #143
### Frontend
- [x] [Adicionar botão para remover unidades](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/issues/116)

**Comment by well1981** [comment]
Critérios de aceitação validados (dei o check). A análise está restrita à interface. Alterar a mensagem de exclusão para constar "Tem certeza que deseja excluir **a** unidade Gama?".

**Comment by senaarth** [comment]
Boa noite @well1981, a história já está implementada e disponível para validação, segue link de teste:

https://develop--capju.netlify.app/

Assim que possível favor retornar com seus comentários.

**Comment by well1981** [comment]
Valido a implementação da US08. Sem observações.
