### ISSUE TITLE
US09 - Gerencionamento de diretores

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#71]
## Descrição.
**Eu como:** Administrador 
**desejo:** gerenciar diretores de unidades  
**para que eu possa:** atribuir e gerenciar diretores de unidades

## Protótipo 
[Tela com listagem de diretores da unidade](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-3434&scaling=min-zoom&page-id=148%3A2857)
[Tela para adicionar diretores em Unidade](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-3609&scaling=min-zoom&page-id=148%3A2857)
[Visualizar diretores adicionados às suas respectivas unidades](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-2769&scaling=min-zoom&page-id=148%3A2857)
[Recusar pedidos para se tornar diretores](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-4414&scaling=min-zoom&page-id=148%3A2857)
[Tela para atribuir usuários como diretor](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-4870&scaling=min-zoom&page-id=148%3A2857)
[Tela para remover permissão de diretor do usuário](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=262-4870&scaling=min-zoom&page-id=148%3A2857)

## Prioridade 
**SHOULD**
  
## Critérios de aceitação

- [x] Visualizar lista com diretores das unidades
- [x] Visualizar solicitações para se tornar diretor
- [x] Solicitações para perfil de diretor aceitas devem atualizar perfil do usuário para ser diretor
- [x] Solicitações para perfil de diretor recusadas **não** devem atualizar perfil do usuário 
- [x] Usuário removidos do perfil de diretor não devem ter acesso de diretor. 

### Protótipo
- [x] #144

**Comment by senaarth** [comment]
Vale lembrar que essa issue se trata **principalmente** da mudança da tela de unidades, onde antes víamos Administradores por unidade devemos ver agora Diretores por Unidade, assim como na visão de adicionar novos. Fazendo com que **só haja um usuário com papel de administrador** na plataforma

**Comment by well1981** [comment]
A minha sugestão foi de termos uma reunião para tratarmos especificamente dessa alteração relacionada ao administrador e diretor. É que não se trata apenas de alterar um pelo outro. É preciso definir diretrizes. Aguardo o encontro. Sem validação para o item.

**Comment by senaarth** [comment]
Boa noite @well1981, a história já está implementada e disponível para validação, segue link de teste:

https://develop--capju.netlify.app/

Assim que possível favor retornar com seus comentários.

**Comment by well1981** [comment]
Valido a implementação da US09 com a criação da aba CADASTRO. Sem observações.
