### ISSUE TITLE
US10 - Gerenciamento de fluxos

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#72]
## Descrição.
Eu como: Servidor, Diretor, Administrador
desejo ter:  separar fluxos por unidade
para que eu possa: gerenciar fluxos nas suas unidades

## Protótipo 
[Tela de visualização de Fluxos](https://www.figma.com/proto/Boim36mSfMhYFTPN7D4VVM/CAPJu---Prot%C3%B3tipos?type=design&node-id=29-4477&scaling=min-zoom&page-id=0%3A1)
  
## Prioridade 
**MUST**

## Critérios de aceitação

- [x] Visualizar somente fluxos referentes a Unidade do Usuário em questão

### Protótipo
- [ ]  Construir Protótipo US10 
## Backend
- [x] #113

**Comment by well1981** [comment]
Critérios de aceitação validados (dei o check). A análise está restrita à interface e levando em consideração a observação do senaarth.

**Comment by senaarth** [comment]
Boa noite @well1981, a história já está implementada e disponível para validação, segue link de teste:

https://develop--capju.netlify.app/

Assim que possível favor retornar com seus comentários.

**Comment by well1981** [comment]
Valido a implementação da US10 (visualizar somente o fluxo da sua unidade). Observações:
- O Administrador não pode ser vinculado a nenhuma unidade;
- As abas etapas, fluxos e processos devem ser desabilitadas para o Administrador;
- O Administrador deve conseguir alterar a unidade do usuário em "Atualizar Perfil de Usuário";
- A US10 deve ser replicada para etapas, processos e cadastro (visualizar somente as informações da unidade).
