### ISSUE TITLE
US15 - Visualização data de vencimento

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#82]
## Descrição.

**Eu como:** Estagiário, Servidor, Diretor, Juiz, Administrador
**desejo:** visualizar a data de vencimento da etapa
**para que eu possa:** rastrear o vencimento de uma etapa

## Prioridade
**Must**
  
## Critérios de aceitação

- [ ] Criterio 1
- [ ] Criterio 2

### Protótipo
- [ ] Construir Protótipo US15

**Comment by well1981** [comment]
Válido a implementação com as seguintes observações: o texto explicativo deve estar no tutorial; alterar texto da caixa (resumido: nome e vencimento).
