### ISSUE TITLE
US16 - Visualização do tutorial

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#83]
## Descrição.
Eu como: Estágiario, Servidor, Diretor, Juiz, Administrador	 
desejo:  visualizar um tutorial informativo sobre o site
para que eu possa: ter informações sobre funcionalidades da aplicação	

## Protótipo
[Tela de unidades como exemplo com botão de saiba mais](https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2392-5876&scaling=min-zoom&page-id=2102%3A2109)
[Tela de unidades como exemplo com modal de saiba mais aberto](https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2395-5976&scaling=min-zoom&page-id=2102%3A2109)

## Prioridade
**Could**
  
## Critérios de aceitação

- [x] Deve haver um texto informativo para cada página de utilização da plataforma

**Comment by well1981** [comment]
Válido o critério de aceitação e o protótipo apresentado com a seguinte observação: mudar o botão "?" para o canto direito inferior.

**Comment by senaarth** [comment]
Implementação disponível para teste no link https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Valido a implementação desta US.
