### ISSUE TITLE
US17 - Visualização de feedbacks por ações

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#84]
## Descrição.

**Eu como:** Estagiário, Servidor, Diretor, Juiz, Administrador
**desejo:** Visualizar feedbacks visuais ao realizar ações
**para que eu possa:** Ter de forma clara informativos sobre ações realizadas

## Prioridade
**MUST**
  
## Critérios de aceitação

- [ ] Critério 1
- [ ] Critério 2

## Protótipo
- [ ] Construir protótipo US17

**Comment by senaarth** [comment]
Fechada por duplicidade com a us19 (#84)
