### ISSUE TITLE
US18 - Visualização de contribuidores

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#85]
## Descrição.

**Eu como:** Estagiário, Servidor, Diretor, Juiz, Administrador
**desejo:** visualizar informações de desenvolvimento da aplicação
**para que eu possa:** ter informações sobre as instituições envolvidas

## Critérios de aceitação

- [x] Deve haver uma página de sobre informando os envolvidos no desenvolvimento da plataforma e também as informações gerais sobre o capju

## Tarefas:
- [ ] Construir Protótipo US18
- [ ] Construir interface nova com um link no header, tanto para usuários autenticados quanto não autenticados
- [ ] Testes automatizados para garantir que a tela renderiza corretamente

**Comment by well1981** [comment]
Válido o critério de aceitação. Segue exemplo:
![image](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/121133676/2ada98d4-b86e-4061-a326-fde562308000)

**Comment by well1981** [comment]
Correto a aba de navegação "sobre".

Referências sem foto e com nome (alunos). Idealizador e Desenvolvedores (responsável técnico) sem foto e com nome e e-mail. Idealizador: Wellington José Barbosa Carlos (wellington.carlos@trf1.jus.br). Hilmer...

Válido o protótipo.

**Comment by senaarth** [comment]
Implementação disponível para teste no link https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Valido a implementação desta US.
