### ISSUE TITLE
US19 - Visualização de indicações

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#86]
## Descrição.
Eu como: Todos os usuários	
desejo:  visualizar indicações sobre criação de etapas durante o fluxo
para que eu possa: ter de forma clara informativos sobre ações realizadas	

## Critérios de aceitação

- [x] As mensagens de sucesso devem estar padronizadas e corretas para todas as ações
- [x] As mensagens de erro devem estar padronizadas e corretas para todas as ações
- [x] Os textos devem estar padronizados para todas as informações 

## Tarefas
- [ ] Corrigir mensagens de erro nas tratativas do backend
- [ ] Corrigir mensagens de erro nas tratativas do frontend
- [ ] Testes automatizados

**Comment by well1981** [comment]
Válido o critério de aceitação.

**Comment by senaarth** [comment]
Implementação disponível para teste no link https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Valido a implementação desta US.
