### ISSUE TITLE
US25 - Gerenciar perfis

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#92]
## Descrição.
Eu como: Administrador 
desejo:  gerenciar perfis de usuários
para que eu possa: atribuir permissões para cada perfil de acesso

## Protótipo
[Tela de perfis de acesso](https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2449-6076&scaling=min-zoom&page-id=2102%3A2109)
[Modal de edição de perfil](https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2451-6177&scaling=min-zoom&page-id=2102%3A2109)
  
## Critérios de aceitação

- [x] Deve haver uma página de gerência de perfil de acesso 
- [x] Deve ser possível dar/retirar permissões de cada perfil de acesso

**Comment by well1981** [comment]
Válido o critério de aceitação. As permissões devem ser fixas e expostas em um quadro.

**Comment by well1981** [comment]
Sobre o protótipo: 1) seguir a seguinte ordem: estagiário. servidor, diretor e juiz; 2) as permissões precisam ser revisadas; 3) mudar a visualização para modo "tabela"; 4) incluir botão "salvar" com confirmação de alteração; 5) a alteração de permissões aparece apenas para o Administrador.

**Comment by senaarth** [comment]
Link para validar implementação https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Valido a implementação. As alterações foram incluídas e o botão salvar está funcionando.
