### ISSUE TITLE
US26 - Gerenciar permissões

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#93]
## Descrição.
Eu como: Diretor, Administrador
desejo:  gerenciar permissões de usuário por perfil
para que eu possa: criar, editar ou deletar permissões

## Protótipo 
https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu?type=design&node-id=0-1&t=0Y6yIn7FQ3LTIOth-0

## Credenciais de acesso
cpf: [12345678901](tel:12345678901)
senha: 123Teste
  
## Critérios de aceitação

- [ ] Critério 1
- [ ] Critério 2
- [ ] Critério 3

## Tarefas:
Protótipo
- [ ] Construir protótipo US26

**Comment by senaarth** [comment]
Fechado após validação de regras de negócio com o cliente ter demonstrada a não necessidade de implementação.
