### ISSUE TITLE
US28 - Registro sem restrições

### ISSUE THREAD

**Issue by wellpriz** [fga-eps-mds/2023-1-CAPJu-Doc#95]
## Descrição.
Eu como: Administrador
desejo:  registrar sem ter restrições 
para que eu possa: cadastrar as primeiras unidades e diretores do sistema

## Protótipo 
<img width="1679" alt="Screen Shot 2023-06-26 at 20 04 00" src="https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/49957403/792183d7-ad65-4b0b-8a87-016acb6f3dd1">

## Credenciais de acesso
cpf: [12345678901](tel:12345678901)
senha: 123Teste
  
## Critérios de aceitação

- [x] No primeiro acesso do Administrador cujo CPF padrão é 123456789-01 o sistema deve emitir um aviso com a exigência de troca obrigatória do e-mail e senha

## Tarefas:
Protótipo
- [ ] Construir protótipo US28

**Comment by well1981** [comment]
Válido o critério de aceitação.

**Comment by well1981** [comment]
Sobre o protótipo: 1) Faltou o registro de e-mail do Administrador; 2) Trocar título por "Edite seu cadastro" (sugestão).

**Comment by faco400** [comment]
Protótipo atualizado se encontra no seguinte link: https://www.figma.com/proto/VTJhv5YNyrUpQon9O6Ig3a/CAPJu---Rascunhos?type=design&node-id=2470-6201&t=F5G7Do3wQnKxSq7m-1&scaling=min-zoom&page-id=2102%3A2109&mode=design

# imagem
![image](https://github.com/fga-eps-mds/2023-1-CAPJu-Doc/assets/49957412/02cf660d-8458-4dfc-ade5-85249a1e0b72)

**Comment by senaarth** [comment]
link para validação da implementação https://develop--capju.netlify.app/

**Comment by well1981** [comment]
Fiz o acesso como administrador (CPF 123456789-01 e senha 123Teste) e não apareceu a opção de alterar a senha e cadastrar e-mail para o primeiro acesso.

**Comment by well1981** [comment]
Após novo teste, foi possível confirmar a implementação desta US. Valido a implementação.
